from pathlib import Path
import shlex
from typing import Optional

from rich import print
import typer
import traceback
from typer.models import OptionInfo

from robotick.launcher.config import Config
from robotick.launcher.utils import copy_extras_for_target, write_text_if_changed
from robotick.launcher.actions.launch import (
    generate_main_cpp,
    generate_model_cpp,
    generate_cmake,
    generate_workloads_registry,
)
from robotick.launcher.actions.launch import (
    prepare_project_workspace as prepare_project_workspace_stage,
)
from robotick.launcher.actions.launch.prepare_project_docker import (
    load_prepared_project_docker_info,
    prepare_project_docker,
)
from robotick.launcher.actions.launch.stages import (
    CUSTOM_STAGE_COMMAND_KEY_BY_STAGE,
    CUSTOM_STAGE_SCRIPT_NAME_BY_STAGE,
    LaunchStage,
)

CUSTOM_STAGE_OVERRIDE_MARKER = "# Generated by launcher from runtime.custom_stages"

_CODEGEN_FLAG_DEFAULTS: dict[str, bool] = {
    "generate_main_cpp": True,
    "generate_model_cpp": True,
    "generate_workload_registry": True,
    "generate_project_cmake": True,
    "generate_component_cmake": True,
}


def resolve_codegen_flags(config: Config) -> dict[str, bool]:
    """Return per-artifact codegen flags for the current model.

    Models can opt out of standalone launcher artifacts when another runtime
    owns the executable entrypoint, for example a ROS2 package.
    """

    runtime = dict((config.model or {}).get("runtime") or {})
    codegen_cfg = runtime.get("codegen") or {}
    if not isinstance(codegen_cfg, dict):
        raise ValueError("Model runtime.codegen must be a mapping when provided.")

    flags = dict(_CODEGEN_FLAG_DEFAULTS)
    for key in flags:
        value = codegen_cfg.get(key)
        if value is None:
            continue
        if not isinstance(value, bool):
            raise ValueError(f"Model runtime.codegen.{key} must be a boolean.")
        flags[key] = value

    return flags


def _resolve_project_local_path(config: Config, raw_path: str) -> Path:
    value = str(raw_path).replace("${PROJECT_DIR}", str(config.project_dir))
    path = Path(value)
    if not path.is_absolute():
        path = config.base_dir / path
    return path.resolve()


def _remove_managed_custom_stage_script_if_needed(
    config: Config, script_path: Path
) -> None:
    if not script_path.exists():
        return

    try:
        content = script_path.read_text(encoding="utf-8")
    except Exception:
        return

    if CUSTOM_STAGE_OVERRIDE_MARKER not in content:
        return

    if config.dry_run:
        print(
            f"[grey]📝 Dry run — would remove stale custom stage script:[/] {script_path}"
        )
        return

    script_path.unlink()
    print(f"[cyan]📝 Removed stale custom stage script:[/] {script_path}")


def _write_custom_stage_override_scripts_if_needed(config: Config) -> None:
    runtime = dict((config.model or {}).get("runtime") or {})
    stages_cfg = runtime.get("custom_stages") or {}
    if not isinstance(stages_cfg, dict):
        raise ValueError("Model runtime.custom_stages must be a mapping when provided.")

    for stage, stage_key in CUSTOM_STAGE_COMMAND_KEY_BY_STAGE.items():
        script_name = CUSTOM_STAGE_SCRIPT_NAME_BY_STAGE[stage]
        script_path = config.launcher_dir / script_name
        command_raw = stages_cfg.get(stage_key)
        if command_raw is None:
            _remove_managed_custom_stage_script_if_needed(config, script_path)
            continue
        if not isinstance(command_raw, str) or not command_raw.strip():
            raise ValueError(
                f"Model runtime.custom_stages.{stage_key} must be a non-empty string when provided."
            )

        command_resolved = command_raw.replace(
            "${PROJECT_DIR}", str(config.project_dir)
        ).strip()
        script_contents = "\n".join(
            [
                "#!/bin/bash",
                "set -euo pipefail",
                "",
                CUSTOM_STAGE_OVERRIDE_MARKER,
                'SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"',
                f"PROJECT_DIR={shlex.quote(str(config.project_dir))}",
                'cd "$PROJECT_DIR"',
                f"exec bash -lc {shlex.quote(command_resolved)}",
                "",
            ]
        )

        if config.dry_run:
            print(
                f"[grey]📝 Dry run — would write custom stage script:[/] {script_path}"
            )
            continue

        write_text_if_changed(script_path, script_contents)
        script_path.chmod(0o755)


def write_launcher_env_if_needed(config: Config) -> None:
    launcher_env = config.launcher_dir / "launcher.env"

    env_lines: list[str] = []
    runtime = dict((config.model or {}).get("runtime") or {})
    deploy = dict(runtime.get("deploy") or {})
    target_variant = str(runtime.get("target_variant") or "").strip().lower()

    if config.target == "esp32":
        env_lines.append("# Generated from model runtime metadata.")

        prepared_project_docker = load_prepared_project_docker_info(
            config.project_name,
            config.model_name,
            config.target,
            config.base_dir,
        )
        # ESP helper scripts run inside Docker. Export the resolved local
        # project-target image so those scripts can prefer it over the shared
        # base image when project-specific deps have been baked in.
        if prepared_project_docker is not None:
            env_lines.append(
                f'export ROBOTICK_PROJECT_DOCKER_IMAGE="{prepared_project_docker.image_name}"'
            )

        engine_local_path = str(
            dict((config.runtime or {}).get("engine") or {}).get("local_path") or ""
        ).strip()
        if engine_local_path:
            engine_root = _resolve_project_local_path(config, engine_local_path)
            env_lines.append(f'export ROBOTICK_ENGINE_PATH="{engine_root}"')

        serial_port = str(deploy.get("serial_port") or "").strip()
        if serial_port:
            env_lines.append(f'export ROBOTICK_ESP32_SERIAL_PORT="{serial_port}"')

        if target_variant == "esp32s3_m5":
            env_lines.append("export ROBOTICK_PLATFORM_ESP32S3_M5=1")
            env_lines.append(
                'export IDF_EXTRA_CMAKE_ARGS="-DROBOTICK_PLATFORM_ESP32S3=ON -DROBOTICK_PLATFORM_ESP32S3_M5=ON"'
            )

    if env_lines:
        contents = "\n".join(env_lines) + "\n"
        if config.dry_run:
            print(f"[grey]📝 Dry run — would write launcher env:[/] {launcher_env}")
        else:
            write_text_if_changed(launcher_env, contents)
        return

    if launcher_env.exists():
        if config.dry_run:
            print(f"[grey]📝 Would remove stale file:[/] {launcher_env}")
        else:
            launcher_env.unlink()
            print(f"[cyan]📝 Removed stale file:[/] {launcher_env}")


def generate(
    project: str = typer.Argument(..., help="Project name (e.g. 'my_robot')"),
    model: str = typer.Argument(..., help="Model name (e.g. 'my_robot_brain')"),
    target: str = typer.Argument(..., help="Target name (e.g. 'linux')"),
    base_dir: Path = typer.Option(
        Path.cwd(), help="Base directory to create .launcher folder under"
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Show what would be created without creating it"
    ),
    stub_install: bool = typer.Option(
        False,
        "--stub-install",
        help="Only create target-folder for each installed dependency, not full install",
    ),
    workspace_dir: Optional[Path] = typer.Option(
        None, help="Workspace root containing the .launcher folder"
    ),
    skip_prepare_project_workspace: bool = False,
    skip_prepare_project_docker: bool = False,
):
    """
    Generate the .launcher folder structure and files for one project/model/target.

    The generation flow now has a strict preparation order:

    1. prepare-project-docker resolves the immutable container environment
    2. prepare-project-workspace hydrates mutable .launcher workspace state
    3. file generation writes the launcher-facing sources and scripts
    """

    try:
        if isinstance(workspace_dir, OptionInfo):
            workspace_dir = None

        base_dir = base_dir.resolve()
        workspace_root = (workspace_dir or base_dir).resolve()
        # Resolve the local project-target image first so later generation can
        # embed any image-specific information needed by helper scripts.
        if not skip_prepare_project_docker:
            prepare_project_docker(
                project=project,
                base_dir=base_dir,
                target=target,
                model=model,
                dry_run=dry_run,
                stub_install=stub_install,
            )
        # Workspace hydration remains separate because it writes persistent
        # mutable state under the bind-mounted .launcher directory.
        if not skip_prepare_project_workspace:
            prepare_project_workspace_stage.prepare_project_workspace(
                project=project,
                base_dir=base_dir,
                workspace_root=workspace_root,
                dry_run=dry_run,
                stub_install=stub_install,
                model=model,
                target=target,
            )

        config = Config(project, model, target, base_dir, dry_run, stub_install)
        target_variant = str(
            ((config.model or {}).get("runtime") or {}).get("target_variant") or ""
        ).strip()

        print(
            "============================================================================================"
        )
        print(
            f"[bold green]📦 Generating {project}-{model}-{target}[/] (dry_run={dry_run}, stub_install={config.stub_install})"
        )

        # ESP32 generation still uses a component-style layout that differs from linux builds.
        # Keep those file-placement overrides centralized here until target layout becomes fully declarative.
        if target == "esp32":
            config.subdir_main_cpp = "main"
            config.subdir_model_cpp = "main"
            config.subdir_registry = "main"
            config.should_generate_workload_deps = False
            config.should_generate_component_cmakelists = True
            config.subdir_component_cmakelists = "main"
        else:
            config.should_generate_workload_deps = True
            config.should_generate_component_cmakelists = False

        # Folder creation
        config.launcher_dir.mkdir(parents=True, exist_ok=True)
        print(f"[green]📂 Launcher folder:[/] {config.launcher_dir}")

        # File generation
        copy_extras_for_target(config, variant=target_variant)
        _write_custom_stage_override_scripts_if_needed(config)
        write_launcher_env_if_needed(config)
        codegen_flags = resolve_codegen_flags(config)
        if codegen_flags["generate_main_cpp"]:
            generate_main_cpp.generate_main_cpp(config)
        if codegen_flags["generate_model_cpp"]:
            generate_model_cpp.generate_model_cpp(config)
        if codegen_flags["generate_workload_registry"]:
            generate_workloads_registry.generate_workloads_registry(config)
        if codegen_flags["generate_project_cmake"]:
            generate_cmake.generate_project_cmakelists(config)
        if codegen_flags["generate_component_cmake"]:
            generate_cmake.generate_component_cmakelists(config)

        print(f"[bold green]✅ Generating complete!")

    except Exception as e:  # pragma: no cover - Typer handles surfacing this
        print(f"[bold red]❌ Generation failed with error:[/] {type(e).__name__}: {e}")
        traceback.print_exc()
        raise typer.Exit(code=1)
