# Auto-generated by launcher: aggregated per-workload dependencies

if(NOT DEFINED ROBOTICK_MAIN_TARGET)
  message(FATAL_ERROR "ROBOTICK_MAIN_TARGET must be set before including generated_workload_deps.cmake")
endif()

if(NOT DEFINED ROBOTICK_EXECUTABLE_TARGET)
  message(FATAL_ERROR "ROBOTICK_EXECUTABLE_TARGET must be set before including generated_workload_deps.cmake")
endif()

include(/home/paulwconnor-ai/dev/robotick/robotick-launcher/tests/test_data/workloads/cpp/src/robotick/workloads/auditory/SpeechToTextWorkload.cmake)

find_package(SDL2 2.0.14 REQUIRED)
find_package(OpenCV REQUIRED)
find_package(PkgConfig REQUIRED)

pkg_check_modules(SDL2_GFX REQUIRED SDL2_gfx)

foreach(_target IN ITEMS ${ROBOTICK_MAIN_TARGET} ${ROBOTICK_EXECUTABLE_TARGET})
  target_include_directories(${_target} PRIVATE ${SDL2_GFX_INCLUDE_DIRS})
  target_link_libraries(${_target} PRIVATE ${SDL2_GFX_LIBRARIES})
endforeach()

pkg_check_modules(SDL2_TTF REQUIRED SDL2_ttf)

foreach(_target IN ITEMS ${ROBOTICK_MAIN_TARGET} ${ROBOTICK_EXECUTABLE_TARGET})
  target_include_directories(${_target} PRIVATE ${SDL2_TTF_INCLUDE_DIRS})
  target_link_libraries(${_target} PRIVATE ${SDL2_TTF_LIBRARIES})
endforeach()

foreach(_target IN ITEMS ${ROBOTICK_MAIN_TARGET} ${ROBOTICK_EXECUTABLE_TARGET})
  target_include_directories(${_target} PRIVATE
    ${OpenCV_INCLUDE_DIRS}
  )
endforeach()

foreach(_target IN ITEMS ${ROBOTICK_MAIN_TARGET} ${ROBOTICK_EXECUTABLE_TARGET})
  target_link_libraries(${_target} PRIVATE
    SDL2::SDL2
    ${OpenCV_LIBS}
    whisper
  )
endforeach()

set(ROBOTICK_HOST_APT libsdl2-dev libopencv-dev)
