import React from "react";

export type WarpMode = "value" | "time" | "time+value";

export type AnimationToolId = "Pencil" | "Line" | "Range" | "Warp" | "Smooth";

export type AnimationToolSettingsContext = {
  durationSec: number;
  lineSnapStart: boolean;
  lineSnapEnd: boolean;
  setLineSnapStart: React.Dispatch<React.SetStateAction<boolean>>;
  setLineSnapEnd: React.Dispatch<React.SetStateAction<boolean>>;
  rangeMidpointSec: number;
  rangeMidpointDraft: string;
  setRangeMidpointDraft: React.Dispatch<React.SetStateAction<string>>;
  setSelectedTimeRangeMidpointSec: (nextMidpointSec: number) => void;
  rangeSizeSec: number;
  rangeSizeDraft: string;
  setRangeSizeDraft: React.Dispatch<React.SetStateAction<string>>;
  setSelectedTimeRangeDurationSec: (nextDurationSec: number) => void;
  rangeFalloffSec: number;
  rangeFalloffDraft: string;
  setRangeFalloffDraft: React.Dispatch<React.SetStateAction<string>>;
  setRangeFalloffSec: React.Dispatch<React.SetStateAction<number>>;
  rangeFalloffCurve: number;
  rangeFalloffCurveDraft: string;
  setRangeFalloffCurveDraft: React.Dispatch<React.SetStateAction<string>>;
  setRangeFalloffCurve: React.Dispatch<React.SetStateAction<number>>;
  warpMode: WarpMode;
  setWarpMode: React.Dispatch<React.SetStateAction<WarpMode>>;
  warpTimeStrength: number;
  warpTimeStrengthDraft: string;
  setWarpTimeStrengthDraft: React.Dispatch<React.SetStateAction<string>>;
  setWarpTimeStrength: React.Dispatch<React.SetStateAction<number>>;
  warpValueStrength: number;
  warpValueStrengthDraft: string;
  setWarpValueStrengthDraft: React.Dispatch<React.SetStateAction<string>>;
  setWarpValueStrength: React.Dispatch<React.SetStateAction<number>>;
  warpLockEndpoints: boolean;
  setWarpLockEndpoints: React.Dispatch<React.SetStateAction<boolean>>;
  smoothRangeSec: number;
  smoothRangeDraft: string;
  setSmoothRangeDraft: React.Dispatch<React.SetStateAction<string>>;
  setSmoothRangeSec: React.Dispatch<React.SetStateAction<number>>;
  smoothFalloffSec: number;
  smoothFalloffDraft: string;
  setSmoothFalloffDraft: React.Dispatch<React.SetStateAction<string>>;
  setSmoothFalloffSec: React.Dispatch<React.SetStateAction<number>>;
  smoothFalloffCurve: number;
  smoothFalloffCurveDraft: string;
  setSmoothFalloffCurveDraft: React.Dispatch<React.SetStateAction<string>>;
  setSmoothFalloffCurve: React.Dispatch<React.SetStateAction<number>>;
  smoothStrength: number;
  smoothStrengthDraft: string;
  setSmoothStrengthDraft: React.Dispatch<React.SetStateAction<string>>;
  setSmoothStrength: React.Dispatch<React.SetStateAction<number>>;
  smoothApplyRateHz: number;
  smoothApplyRateDraft: string;
  setSmoothApplyRateDraft: React.Dispatch<React.SetStateAction<string>>;
  setSmoothApplyRateHz: React.Dispatch<React.SetStateAction<number>>;
  smoothRangeStepSec: number;
  rangeFalloffStepSec: number;
};

export type AnimationToolDefinition = {
  id: string;
  label: string;
  section: string;
  enabled: boolean;
  description: string;
  renderSettings?: (context: AnimationToolSettingsContext) => React.ReactNode;
};
