# Auto-generated by launcher: aggregated per-workload dependencies

if(NOT DEFINED ROBOTICK_MAIN_TARGET)
  message(FATAL_ERROR "ROBOTICK_MAIN_TARGET must be set before including generated_workload_deps.cmake")
endif()

if(NOT DEFINED ROBOTICK_EXECUTABLE_TARGET)
  message(FATAL_ERROR "ROBOTICK_EXECUTABLE_TARGET must be set before including generated_workload_deps.cmake")
endif()
{% if workload_cmakes|length > 0 %}

{# --- manual workload cmake includes --- #}
{% for workload_cmake in workload_cmakes %}
include({{workload_cmake}})
{% endfor %}
{% endif %}

{# --- find_package (with optional version) --- #}
{% for p in find_required -%}
find_package({{p.name}}{% if p.version_sanitized %} {{p.version_sanitized}}{% endif %}{% if p.components and p.components|length %} COMPONENTS {{ ' '.join(p.components) }}{% endif %} REQUIRED)
{% endfor -%}

{# --- pkg-config modules --- #}
{% if pkg_config|length > 0 %}
find_package(PkgConfig REQUIRED)

{% for prefix, module in pkg_config.items() %}
pkg_check_modules({{ prefix }} REQUIRED {{ module }})

foreach(_target IN ITEMS ${ROBOTICK_MAIN_TARGET} ${ROBOTICK_EXECUTABLE_TARGET})
  target_include_directories(${_target} PRIVATE {{ '${' ~ prefix ~ '_INCLUDE_DIRS}' }})
  target_link_libraries(${_target} PRIVATE {{ '${' ~ prefix ~ '_LIBRARIES}' }})
endforeach()

{% endfor %}
{% endif %}
{% for depname, opts in cmake_options.items() %}
# Options for {{ depname }}
{% for key, val in opts.items() %}
set({{ key }} {{ val }} CACHE {{ 'BOOL' if val in ['ON','OFF'] else 'STRING' }} "" FORCE)

{% endfor %}
{% endfor %}
{% for depname, subdir in git_subdirs %}
# {{ depname }}
add_subdirectory("{{ subdir }}")

{% endfor %}
{# --- manual include dirs (rare; prefer imported targets) --- #}
{% if include_dirs|length > 0 %}
foreach(_target IN ITEMS ${ROBOTICK_MAIN_TARGET} ${ROBOTICK_EXECUTABLE_TARGET})
  target_include_directories(${_target} PRIVATE
{% for inc in include_dirs %}    {{ inc }}
{% endfor %}  )
endforeach()
{% endif %}

{# --- imported CMake targets (SDL2::SDL2, OpenCV::opencv, etc.) --- #}
{% if link_targets|length > 0 %}
foreach(_target IN ITEMS ${ROBOTICK_MAIN_TARGET} ${ROBOTICK_EXECUTABLE_TARGET})
  target_link_libraries(${_target} PRIVATE
{% for t in link_targets %}    {{ t }}
{% endfor %}  )
endforeach()
{% endif %}

{# --- provisioning hints (toolchain/docs) --- #}
{% if idf_components|length > 0 %}
set(ROBOTICK_IDF_COMPONENTS {{ idf_components | join(' ') }})
{% endif %}
{% if host_apt|length > 0 %}
set(ROBOTICK_HOST_APT {{ host_apt | join(' ') }})
{% endif %}
